name: my-workflow

on:
  workflow_dispatch:

jobs:
  exicuting-the-cammand:
    runs-on: ubuntu-latest
    steps:

       - name: checkout
         uses: actions/checkout@v6.0.1
       - name: exicuting the ls cammand
         run: ls -a
